### ISSUE TITLE
'Wrong username' should not be a functionality

### ISSUE THREAD

**Issue by henrizhang** [vliok/HW4#1]
This an unnecessary feature that introduces security problems: 

``` python
if username != pair[0] and password == pair[1]:
            f.close()
            return render_template("login.html",message="Wrong username!")
```

Once you know someone's password, it's easy to find the matching user.

For example: I put in 'cats' as the password. If I see 'Wrong username', I am now guaranteed access to at least one account that doesn't belong to me (provided I have a list of usernames).

**Comment by vliok** [comment]
Oops! I thought this was a little strange as well but I guess I just misinterpreted Mr. Brown's instructions.
