### ISSUE TITLE
Unable to Log In as New User

### ISSUE THREAD

**Issue by wxiang54** [vliok/HW4#2]
## Issue

Line 47 causes an issue for any new user (without an existing session), because `session["username"]` will return a _KeyError_ (nothing will be in session yet).
## Proposed Changes
- Check if a key called "username" exists in _session_ before checking if `session["username"] == username`
## Snippet

``` py
34| for line in f:

...

47|    if session["username"] == username:
48|       return render_template("login.html",message="Already logged in from another computer!")
```

> Note: I may be diving into pedantry here, but no two computers will ever be in the same session, so if `session["username"] == username`, it doesn't mean you're logged in from another computer, rather you're already logged in here and you somehow got back to the login page without logging out.

**Comment by vliok** [comment]
Alright thanks! You cleared up my confusion with the concept of a "session".
